const source = (label, url) => ({ label, url });
// This is the inspectable research cache. Each claim is linked to a first-party public source.
const accounts = [
  { name: 'Vale', country: 'Brazil', commodity: 'Iron ore', score: 94, fit: 'SQM-scale, multi-site Latin American miner with iron ore, pellet and logistics operations. The scale and distributed critical infrastructure make repeatable remote inspection relevant.', signals: ['Carlos Medeiros oversees Vale mining, pellet production and logistics as Executive VP Operations.', 'Vale publicly identifies a technical EVP focused on dam and tailings management, a high-consequence inspection context.'], news: 'Leadership and operational remit are current on Vale’s executive leadership page.', tech: 'Strong fit: mining, pellet and logistics operations create recurring inspection routes across hazardous infrastructure.', sources: [source('Vale leadership', 'https://www.vale.com/leadership')], contacts: [{ name: 'Carlos Medeiros', role: 'Executive Vice President - Operations', verification: 'Verified on Vale leadership page', link: 'https://www.vale.com/leadership' }, { name: 'Rafael Bittar', role: 'Executive Vice President - Technical', verification: 'Verified on Vale leadership page; tailings-management background', link: 'https://www.vale.com/leadership' }] },
  { name: 'Nexa Resources', country: 'Brazil & Peru', commodity: 'Zinc, copper, lead', score: 91, fit: 'Latin American mining and metallurgy operator with five mines and three smelters across Brazil and Peru. It combines hazardous underground mining with processing infrastructure.', signals: ['Nexa reports eight operations: five mines and three smelters, including Cerro Lindo, Peru’s largest underground zinc mine.', 'Nexa reported US$352m in 2025 CAPEX and record quarterly production from Aripuana.'], news: '2025 performance and 2026 production results are published on Nexa’s public site.', tech: 'Strong fit: underground mine and smelter footprint gives Operations a repeatable safety and reliability inspection problem.', sources: [source('Nexa operations', 'https://www.nexaresources.com/en/about-us/'), source('Nexa leadership', 'https://ri.nexaresources.com/corporate-governance/leadership-team/')], contacts: [{ name: 'Leonardo Nunes Coelho', role: 'Senior Vice President of Mining Operations', verification: 'Verified on Nexa leadership page', link: 'https://ri.nexaresources.com/corporate-governance/leadership-team/' }, { name: 'Fernando Demuner', role: 'Smelting Operations Officer', verification: 'Verified on Nexa leadership page', link: 'https://ri.nexaresources.com/corporate-governance/leadership-team/' }] },
  { name: 'Antofagasta Minerals', country: 'Chile', commodity: 'Copper', score: 89, fit: 'A Chile-based top-ten copper producer operating four open-pit mines. Its geography, mining scale, and 24/7 processing profile closely parallel SQM’s operational setting.', signals: ['Antofagasta operates Los Pelambres, Centinela, Antucoya and Zaldívar in Chile.', 'Los Pelambres produced 319.6kt copper in 2024 and employs a workforce of 7,711; Centinela produced 223.8kt and has 8,992 workers.', 'The group has reported field leadership, contractor-management and critical-risk-control initiatives.'], news: 'The company reported a July 2026 weather-driven operational shutdown and controlled restart at Los Pelambres.', tech: 'Strong fit: large open-pit sites, processing plants, tailings and weather exposure create a concrete case for autonomous site visibility.', sources: [source('Antofagasta sustainability report', 'https://sr.antofagasta.co.uk/'), source('Los Pelambres update', 'https://www.antofagasta.co.uk/investors/news/2026/los-pelambres-operational-update/')], contacts: [{ name: 'Contact research required', role: 'Site Operations / HSE leader', verification: 'No named target-role contact was verified from a first-party public leadership source. The workflow intentionally suppresses a guessed persona.', link: 'https://www.antofagasta.co.uk/about-us/our-approach/our-approach-to-risk/' }] }
];

const $ = s => document.querySelector(s);
function emailFor(account, contact) {
  const first = contact.name.split(' ')[0];
  const evidence = account.name === 'Vale' ? 'Vale’s mining, pellet and logistics remit' : account.name === 'Nexa Resources' ? 'Nexa’s five mines and three smelters across Brazil and Peru' : 'the scale of your Chilean copper operations';
  const focus = account.name === 'Antofagasta Minerals' ? 'weather resilience, tailings and plant visibility' : 'safer, more frequent inspection of critical assets';
  return { subject: `${account.name}: autonomous inspection at operating scale`, body: `Hi ${first},\n\nI noticed ${evidence}. That is the kind of distributed, high-consequence operating environment where teams are asked to improve ${focus} without adding contractor exposure.\n\nFlytBase helps industrial teams run autonomous drone operations from a central control layer. Shell, Anglo American and CSX use FlytBase in mission-critical environments where inspections need to happen consistently, including outside normal access windows.\n\nWould a 20-minute conversation on how this could apply to ${account.name}'s operations be useful?\n\nBest,\n[Sender]` };
}
function render() {
  $('#empty').hidden = true; $('#results').hidden = false;
  const contacts = accounts.flatMap(a => a.contacts).filter(c => !c.name.startsWith('Contact'));
  $('#summary').textContent = `${accounts.length} matched accounts, ${contacts.length} verified contacts`;
  $('#metrics').innerHTML = `<div><strong>${accounts.length}</strong><span>Accounts scored</span></div><div><strong>${contacts.length}</strong><span>Verified named contacts</span></div><div><strong>${accounts.reduce((n,a)=>n+a.sources.length,0)}</strong><span>First-party sources</span></div><div><strong>0</strong><span>Guessed emails</span></div>`;
  $('#accounts').innerHTML = accounts.map((a,i) => `<article class="account"><div class="account-top"><div><span class="rank">MATCH ${String(i+1).padStart(2,'0')}</span><h3>${a.name}</h3><p>${a.country} <span>·</span> ${a.commodity}</p></div><div class="score"><strong>${a.score}</strong><small>ICP score</small></div></div><div class="account-grid"><div><h4>Why it fits</h4><p>${a.fit}</p><h4>Evidence</h4><ul>${a.signals.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><h4>Research brief</h4><p><b>Recent signal:</b> ${a.news}</p><p><b>FlytBase relevance:</b> ${a.tech}</p><div class="sources">${a.sources.map(s=>`<a target="_blank" rel="noreferrer" href="${s.url}">↗ ${s.label}</a>`).join('')}</div></div></div><div class="contacts"><h4>Target contacts</h4>${a.contacts.map((c,j)=>{ const e=emailFor(a,c); const safe = !c.name.startsWith('Contact'); return `<details ${safe && i===0 && j===0 ? 'open':''}><summary><span class="person">${safe ? c.name : 'No verified persona'}</span><span>${c.role}</span><span class="verified">${safe ? 'Verified' : 'Needs enrichment'}</span></summary><div class="contact-body"><p><b>Verification:</b> <a target="_blank" rel="noreferrer" href="${c.link}">${c.verification}</a></p>${safe ? `<div class="email"><div><span>GENERATED OUTREACH</span><b>Subject: ${e.subject}</b></div><pre>${e.body}</pre><p class="rationale">Personalization inputs: ${a.signals.slice(0,2).join(' ')}</p></div>` : '<p class="suppressed">No email generated. A named target contact must be confirmed from an authoritative public source before outreach is drafted.</p>'}</div></details>`}).join('')}</div></article>`).join('');
}
function setStages() { const stages = [...document.querySelectorAll('[data-stage]')]; stages.forEach(x => { x.className = ''; x.querySelector('em').textContent='Waiting'; }); stages.forEach((stage, index) => setTimeout(()=>{ stage.className='active'; stage.querySelector('em').textContent='Running'; setTimeout(()=>{ stage.className='done'; stage.querySelector('em').textContent='Complete'; if(index===stages.length-1) render(); }, 650); }, index*720)); }
$('#run').addEventListener('click', () => { $('#run').disabled=true; $('#run').innerHTML='Running research...'; setStages(); setTimeout(()=>{$('#run').disabled=false; $('#run').innerHTML='<span class="play">↻</span> Run again';}, 3300); });
$('#export').addEventListener('click', () => { const blob=new Blob([JSON.stringify({brief:{vertical:$('#vertical').value,reference:$('#reference').value,goal:$('#goal').value,angle:$('#angle').value},accounts},null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='prospect-engine-results.json';a.click();URL.revokeObjectURL(a.href); });
